services:
  discord-keycloak-rolesync:
    image: NotActuallyTerry/discord-keycloak-rolesync
    build:
      context: .
    environment:
      DISCORD_BOT_TOKEN:
      DISCORD_GUILD_ID:
      AUTHENTIK_HOST:
      AUTHENTIK_API_KEY:
    restart: on-failure